name: testing_workflow

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      test: 'test the variable'
    steps:
      - run: "echo $test"
      - run: "sudo apt install nodejs && apt install npm"
      - uses: actions/checkout@v3
      


